### ISSUE TITLE
Roadmap.

### ISSUE THREAD

**Issue by Ben-PH** [Ben-PH/type_eval#16]
0.0.1 is in PR. roadmap for post alpha release:

- [x] run-time expression
- [ ] generative testing (prop-test)
- [ ] decl macro
- [ ] push back MSRV (resolving div requirements)
- [x] modulo
- [x] gcd
- [ ] gcf
- [ ] negatives
- [ ] decimal, with binary as an alternate
- [ ] tuples: (((_1, _0), _0), _1) instead of `B<B<B<_1, _0>, _0>, _1>`
- [ ] to/from with typenum bitstrings (probably feature gated)
- [ ] custom errors

The holy grail:

- [ ] Partial evaluation, including runtime placeholder

For example, `(x + y) + (x + z) == 2x + (y + z)`.

if `x` is provided by side effect, a partial evaluation like so:

`Add<Add<x, Y>, Add<x, Z>>` would be able to monomorphise to a function `fn foo<X, Y>(x: ???) { 2 * x + AddExp<X, Y>}`

...and thus we have started introducing the concepts of side-effect monads into rust, opening the door to a "pure" paradigm for rust.
